# Generated by Django 4.1.5 on 2023-01-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0005_post_situation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='situation',
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
