# Generated by Django 4.1.5 on 2023-01-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0006_remove_post_situation_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='premium',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
