# Generated by Django 4.1.5 on 2023-01-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0010_remove_post_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
