# Generated by Django 4.1.5 on 2023-01-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0013_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=True, upload_to='images/'),
        ),
    ]
