# Generated by Django 4.1.5 on 2023-01-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0016_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='post/'),
        ),
    ]
