# Generated by Django 4.1.5 on 2023-01-09 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0020_profile_cart_lastreviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='telefone',
            new_name='telephone',
        ),
    ]
