# Generated by Django 4.1.5 on 2023-01-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0021_rename_telefone_profile_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
