# Generated by Django 4.1.5 on 2023-01-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0025_profile_slug_alter_verified_photorg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='membersince',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='online',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
