# Generated by Django 4.1.5 on 2023-01-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0029_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
