# Generated by Django 4.1.5 on 2023-01-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0033_rename_profile_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
