# Generated by Django 4.1.5 on 2023-01-12 00:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplication', '0035_bank_acctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='username',
            field=models.ManyToManyField(related_name='bank_username', to=settings.AUTH_USER_MODEL),
        ),
    ]
