# Generated by Django 4.1.5 on 2023-01-12 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0036_bank_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='username',
        ),
    ]
