# Generated by Django 4.1.4 on 2023-01-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0037_remove_bank_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
