# Generated by Django 4.1.4 on 2023-01-13 02:45

import aplication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0042_alter_comment_slug_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=models.SlugField(null=True, verbose_name=aplication.models.Post),
        ),
    ]
