# Generated by Django 4.1.4 on 2023-01-13 02:46

import aplication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplication', '0043_alter_comment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplication.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=models.SlugField(verbose_name=aplication.models.Post),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
