# Generated by Django 4.1.4 on 2023-01-13 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0044_alter_comment_post_alter_comment_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
    ]
