# Generated by Django 4.1.4 on 2023-01-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0046_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
