# Generated by Django 4.1.4 on 2023-01-13 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0049_alter_comment_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='slugpostsave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplication.post')),
            ],
        ),
    ]
